

#
# d53.rds is generated by code below with data_1000000 from 
# https://github.com/statisticsnorway/sdc-census-2021-hypercubes/blob/main/data/data_1000000.RData
# and f1, f2, f3, f4 as below
# set.seed(53)
# d53 <- GaussSuppressionFromData(data = data_1000000[sample.int(1e+06, size = 10000), ], 
#             formula = SSBtools::combine_formulas(list(table_1 = f1, 
#                                                       table_2 = f2,
#                                                       table_3 = f3, 
#                                                       table_4 = f4)), 
#             output = "inner")

test_that("LinkedSuppression", {
  f1 <- ~sex * (age_l + age_m + age_h) * (lms_l + lms_h) 
  f2 <- ~sex * (age_l + age_m + age_h) * (hst_l + hst_m + hst_h) 
  f3 <- ~sex * (age_l + age_m + age_h) * (fst_l + fst_m + fst_h) 
  f4 <- ~sex * (lms_l + lms_h) * (hst_l + hst_m + hst_h)
  d53 <- readRDS(testthat::test_path("testdata", "d53.rds"))
  
  linkedGauss <- "consistent"
  recordAware <- TRUE
  
  a <- LinkedSuppression(data = d53,
                         freqVar = "freq",
                         fun = SuppressSmallCounts,
                         withinArg = list(list(formula = f1),
                                          list(formula = f2),
                                          list(formula = f3),
                                          list(formula = f4)), 
                         recordAware =  recordAware,
                         preAggregate = TRUE,
                         maxN = 3, 
                         protectZeros = FALSE,   extend0 = FALSE, 
                         printXdim = TRUE,
                         singletonMethod = "none",
                         linkedGauss = linkedGauss)
  
  expect_identical(
    sapply(a, function(x) sum(seq_len(nrow(x)) * as.integer(x$suppressed))),
    c(1353576L, 2305412L, 5071277L, 20531L))
  
  
  
  b <- tables_by_formulas(data = d53,
                          freqVar = "freq",
                          table_fun = SuppressSmallCounts,
                          table_formulas = list(table_1 = f1,
                                                table_2 = f2,
                                                table_3 = f3,
                                                table_4 = f4),
                          recordAware =  recordAware,
                          maxN = 3, 
                          protectZeros = FALSE,   extend0 = FALSE, 
                          printXdim = TRUE,
                          singletonMethod = "none",
                          linkedGauss = linkedGauss)
  
  expect_identical(
    sum(seq_len(nrow(b)) * as.integer(b$suppressed)),
    22078558L)
})



